/**
 * @version 2.9.10.3948
 * @noSelf
 **/
export interface _DCS {
	RCD_selectMenuItem(...args: any[]): unknown;
	exitProcess(...args: any[]): unknown;
	UNIT_CALLSIGN: number;
	S_EVENT_SHOT: number;
	getAvailableSlots(...args: any[]): unknown;
	setCameraToAirdrome(...args: any[]): unknown;
	reloadUserScripts(...args: any[]): unknown;
	S_EVENT_UNIT_TASK_COMPLETE: number;
	S_EVENT_SHOOTING_END: number;
	getModelNameByShapeTableIndex(...args: any[]): unknown;
	dModeUser: number;
	setViewRearmPositionType(...args: any[]): unknown;
	isMetricSystem(...args: any[]): unknown;
	getFarpsAndCarriersMissionData(...args: any[]): unknown;
	getGamePattern(...args: any[]): unknown;
	lockAllMouseInput(...args: any[]): unknown;
	getTaintedCategories(...args: any[]): unknown;
	setPause(...args: any[]): unknown;
	getAvailableCoalitions(...args: any[]): unknown;
	setViewRearm(...args: any[]): unknown;
	getMissionLoaded(...args: any[]): unknown;
	conquestCoalitionsScore(...args: any[]): unknown;
	getAirTankerID(...args: any[]): unknown;
	getObjectLiveriesNames(...args: any[]): unknown;
	getManualPath(...args: any[]): unknown;
	S_EVENT_REFUELING_STOP: number;
	getTaintedFiles(...args: any[]): unknown;
	spawnPlayer(...args: any[]): unknown;
	getPause(...args: any[]): unknown;
	activateGroup(...args: any[]): unknown;
	setViewPause(...args: any[]): unknown;
	sendRCD_Callback(...args: any[]): unknown;
	dispatchDigitalAction(...args: any[]): unknown;
	getAircraftAmountInAirportWarehouse(...args: any[]): unknown;
	S_EVENT_WEAPON_REARM: number;
	getTheatreID(...args: any[]): unknown;
	S_EVENT_DETAILED_FAILURE: number;
	getMoonAzimuthElevationPhase(...args: any[]): unknown;
	S_EVENT_HUMAN_FAILURE: number;
	LMSSetWaitForMinimalPlayers(...args: any[]): unknown;
	UIRequestOverlayWidgetPosition(...args: any[]): unknown;
	getDefaultFOV(...args: any[]): unknown;
	S_EVENT_RUNWAY_TOUCH: number;
	S_EVENT_UNIT_CREATE_TASK: number;
	onUserLogin(...args: any[]): unknown;
	getCurrentFOV(...args: any[]): unknown;
	setPlayerUnit(...args: any[]): unknown;
	UNIT_COUNTRY_ID: number;
	makeScreenShot(...args: any[]): unknown;
	UIDeclutterOnOff(...args: any[]): unknown;
	getAirdromesState(...args: any[]): unknown;
	S_EVENT_EJECTION: number;
	hasMultipleSlots(...args: any[]): unknown;
	checkMultiplayerSpawnConflict(...args: any[]): unknown;
	getServerStartTime(...args: any[]): unknown;
	setMainPilot(...args: any[]): unknown;
	S_EVENT_UNIT_LOST: number;
	S_EVENT_INVALID: number;
	getInputNameByUnitType(...args: any[]): unknown;
	S_EVENT_EMERGENCY_LANDING: number;
	S_EVENT_CRASH: number;
	getMissionFilename(...args: any[]): unknown;
	S_EVENT_WEAPON_DROP: number;
	getMissionResourcesDialogData(...args: any[]): unknown;
	isSupercarrierRoleAvailable(...args: any[]): unknown;
	getATCradiosData(...args: any[]): unknown;
	HMD_isActive(...args: any[]): unknown;
	preloadCockpit(...args: any[]): unknown;
	getMainPilot(...args: any[]): unknown;
	S_EVENT_FLIGHT_TIME: number;
	setNeedRestartApplication(...args: any[]): unknown;
	enter_with_dyngroup(...args: any[]): unknown;
	getLogHistory(...args: any[]): unknown;
	S_EVENT_SCORE: number;
	setCurrentFOV(...args: any[]): unknown;
	isSlotFlyable(...args: any[]): unknown;
	getUnitProperty(...args: any[]): unknown;
	S_EVENT_HUMAN_AIRCRAFT_REPAIR_FINISH: number;
	S_EVENT_RUNWAY_TAKEOFF: number;
	setPlayerCoalition(...args: any[]): unknown;
	S_EVENT_SIMULATION_UNFREEZE: number;
	dModeStop: number;
	S_EVENT_SIMULATION_FREEZE: number;
	S_EVENT_MAC_LMS_RESTART: number;
	UNIT_PLAYER_NAME: number;
	getRealTime(...args: any[]): unknown;
	S_EVENT_HUMAN_AIRCRAFT_REPAIR_START: number;
	openHomePage(...args: any[]): unknown;
	S_EVENT_DAYNIGHT: number;
	S_EVENT_MISSION_WINNER: number;
	S_EVENT_MISSION_RESTART: number;
	S_EVENT_KILL: number;
	getMissionTheatre(...args: any[]): unknown;
	S_EVENT_MAC_EXTRA_SCORE: number;
	S_EVENT_UNIT_TASK_STAGE: number;
	S_EVENT_SIMULATION_START: number;
	S_EVENT_UNIT_DELETE_TASK: number;
	S_EVENT_PLAYER_CAPTURE_AIRFIELD: number;
	getInputProfiles(...args: any[]): unknown;
	S_EVENT_PLAYER_SELF_KILL_PILOT: number;
	S_EVENT_DEAD: number;
	S_EVENT_TRIGGER_ZONE: number;
	S_EVENT_AI_ABORT_MISSION: number;
	UNIT_CATEGORY: number;
	lockAllKeyboardInput(...args: any[]): unknown;
	S_EVENT_LANDING_QUALITY_MARK: number;
	lockMouseInput(...args: any[]): unknown;
	getPlayerBriefing(...args: any[]): unknown;
	S_EVENT_WEAPON_ADD: number;
	UNIT_TASK: number;
	setLiveryNameResourcesDialogData(...args: any[]): unknown;
	S_EVENT_DISCARD_CHAIR_AFTER_EJECTION: number;
	getMissionOptions(...args: any[]): unknown;
	S_EVENT_PLAYER_ENTER_UNIT: number;
	getCurrentMission(...args: any[]): unknown;
	S_EVENT_PARATROOPER_LENDING: number;
	dModeInit: number;
	getSunAzimuthElevation(...args: any[]): unknown;
	getSimulatorMode(...args: any[]): unknown;
	S_EVENT_MAX: number;
	S_EVENT_LANDING_AFTER_EJECTION: number;
	S_EVENT_MARK_CHANGE: number;
	takeTrackControl(...args: any[]): unknown;
	S_EVENT_MARK_ADDED: number;
	UNIT_RUNTIME_ID: number;
	S_EVENT_PLAYER_COMMENT: number;
	S_EVENT_PLAYER_LEAVE_UNIT: number;
	S_EVENT_ENGINE_SHUTDOWN: number;
	activateSteamOverlayToStore(...args: any[]): unknown;
	S_EVENT_ENGINE_STARTUP: number;
	getConquestAirbaseState(...args: any[]): unknown;
	refreshPilotStatistics(...args: any[]): unknown;
	S_EVENT_TOOK_CONTROL: number;
	LMSGetRemainingTimeBeforeZoneShrink(...args: any[]): unknown;
	S_EVENT_MISSION_END: number;
	S_EVENT_TAKEOFF: number;
	getDynamicSpawnSettings(...args: any[]): unknown;
	dModeStart: number;
	S_EVENT_BASE_CAPTURED: number;
	unlockMouseInput(...args: any[]): unknown;
	getPlayerUnit(...args: any[]): unknown;
	getHumanUnitInputName(...args: any[]): unknown;
	unlockKeyboardInput(...args: any[]): unknown;
	S_EVENT_REFUELING: number;
	isRoleAvailable(...args: any[]): unknown;
	dispatchAnalogAction(...args: any[]): unknown;
	S_EVENT_LAND: number;
	getPilotsSummaryStatistics(...args: any[]): unknown;
	S_EVENT_MISSION_START: number;
	isMultiplayer(...args: any[]): unknown;
	updaterOperation(...args: any[]): unknown;
	dModeFinish: number;
	S_EVENT_HIT: number;
	dModeWork: number;
	dModePostStart: number;
	UNIT_NAME: number;
	getServerStartTimeRemain(...args: any[]): unknown;
	getAirdromesCoalition(...args: any[]): unknown;
	UNIT_ROLE: number;
	UNIT_COALITION: number;
	isTrackPlaying(...args: any[]): unknown;
	getMissionDescription(...args: any[]): unknown;
	setDebriefingShow(...args: any[]): unknown;
	UNIT_HIDDEN: number;
	stopMission(...args: any[]): unknown;
	UNIT_GROUPNAME: number;
	getMissionResult(...args: any[]): unknown;
	getGameDuration(...args: any[]): unknown;
	UNIT_GROUP_MISSION_ID: number;
	S_EVENT_BDA: number;
	UNIT_TYPE: number;
	create_client_aircraft(...args: any[]): unknown;
	UNIT_MISSION_ID: number;
	S_EVENT_SHOOTING_START: number;
	getAchievementsUiInfo(...args: any[]): unknown;
	getModelTime(...args: any[]): unknown;
	getPlayerCoalition(...args: any[]): unknown;
	setScreenShotExt(...args: any[]): unknown;
	lockKeyboardInput(...args: any[]): unknown;
	getPilotStatistics(...args: any[]): unknown;
	getUnitType(...args: any[]): unknown;
	getInstalledTheatres(...args: any[]): unknown;
	getGeneratedParams(...args: any[]): unknown;
	isHumanSeatAvailable(...args: any[]): unknown;
	UNIT_INVISIBLE_MAP_ICON: number;
	setUserCallbacks(...args: any[]): unknown;
	getPilotAchievements(...args: any[]): unknown;
	getConfigValue(...args: any[]): unknown;
	restartMission(...args: any[]): unknown;
	S_EVENT_PILOT_DEAD: number;
	setViewRearmAnimationTime(...args: any[]): unknown;
	getUserOptions(...args: any[]): unknown;
	setMaxFPS(...args: any[]): unknown;
	isServer(...args: any[]): unknown;
	onShowStatusBar(...args: any[]): unknown;
	selfKillPilot(...args: any[]): unknown;
	unsetViewRearm(...args: any[]): unknown;
	add_dyn_group(...args: any[]): unknown;
	writeDebriefing(...args: any[]): unknown;
	UNIT_GROUPCATEGORY: number;
	MACSavePSData(...args: any[]): unknown;
	setDefaultFOV(...args: any[]): unknown;
	getPlayerUnitType(...args: any[]): unknown;
	LMSRestart(...args: any[]): unknown;
	setBoardNumResourcesDialogData(...args: any[]): unknown;
	reloadOptions(...args: any[]): unknown;
	isSteamVersion(...args: any[]): unknown;
	S_EVENT_BIRTH: number;
	setMissionResourcesDialogData(...args: any[]): unknown;
	S_EVENT_MARK_REMOVED: number;
	getUnitTypeAttribute(...args: any[]): unknown;
	getMissionName(...args: any[]): unknown;
	getMaxFPS(...args: any[]): unknown;
	onShowDialog(...args: any[]): unknown;
}
