/**
 * @version 2.9.29.27468
 * @noSelf
 */
export interface _net {
	CHAT_ALL: number;
	CHAT_TEAM: number;
	ERR_BAD_CALLSIGN: number;
	ERR_BANNED: number;
	ERR_CONNECT_FAILED: number;
	ERR_DENIED_TRIAL_ONLY: number;
	ERR_INVALID_ADDRESS: number;
	ERR_INVALID_PASSWORD: number;
	ERR_KICKED: number;
	ERR_NOT_ALLOWED: number;
	ERR_PROTOCOL_ERROR: number;
	ERR_REFUSED: number;
	ERR_SERVER_FULL: number;
	ERR_TAINTED_CLIENT: number;
	ERR_THATS_OKAY: number;
	ERR_TIMEOUT: number;
	ERR_WRONG_VERSION: number;
	GAME_MODE_CONQUEST: number;
	GAME_MODE_LAST_MAN_STANDING: number;
	GAME_MODE_MISSION: number;
	GAME_MODE_TEAM_DEATH_MATCH: number;
	PS_CAR: number;
	PS_CRASH: number;
	PS_EJECT: number;
	PS_LAND: number;
	PS_PING: number;
	PS_PLANE: number;
	PS_SCORE: number;
	PS_SHIP: number;
	RESUME_MANUAL: number;
	RESUME_ON_LOAD: number;
	RESUME_WITH_CLIENTS: number;
	banlist_add(...args: any[]): unknown;
	banlist_add_by_ucid(...args: any[]): unknown;
	banlist_get(...args: any[]): unknown;
	banlist_remove(...args: any[]): unknown;
	check_ic_requirements(...args: any[]): unknown;
	check_password(...args: any[]): unknown;
	dostring_in(...args: any[]): unknown;
	force_player_slot(...args: any[]): unknown;
	get_chat_history(...args: any[]): unknown;
	get_coalition(...args: any[]): unknown;
	get_default_server_settings(...args: any[]): unknown;
	get_my_player_id(...args: any[]): unknown;
	get_name(...args: any[]): unknown;
	get_player_info(...args: any[]): unknown;
	get_player_list(...args: any[]): unknown;
	get_server_host(...args: any[]): unknown;
	get_server_id(...args: any[]): unknown;
	get_server_settings(...args: any[]): unknown;
	get_server_uptime(...args: any[]): unknown;
	get_session_history(...args: any[]): unknown;
	get_slot(...args: any[]): unknown;
	get_stat(...args: any[]): unknown;
	hash_password(...args: any[]): unknown;
	is_loopback_address(...args: any[]): unknown;
	is_private_address(...args: any[]): unknown;
	json2lua(...args: any[]): unknown;
	kick(...args: any[]): unknown;
	load_mission(...args: any[]): unknown;
	load_next_mission(...args: any[]): unknown;
	log(...args: any[]): unknown;
	lua2json(...args: any[]): unknown;
	missionlist_append(...args: any[]): unknown;
	missionlist_clear(...args: any[]): unknown;
	missionlist_delete(...args: any[]): unknown;
	missionlist_get(...args: any[]): unknown;
	missionlist_get_installed_theatres(...args: any[]): unknown;
	missionlist_move(...args: any[]): unknown;
	missionlist_run(...args: any[]): unknown;
	missionlist_set_loop(...args: any[]): unknown;
	missionlist_set_shuffle(...args: any[]): unknown;
	recv_chat(...args: any[]): unknown;
	resetJoinCooldownEndForAll(...args: any[]): unknown;
	resetJoinCooldownEndForPlayer(...args: any[]): unknown;
	restart(...args: any[]): unknown;
	screenshot_del(...args: any[]): unknown;
	screenshot_request(...args: any[]): unknown;
	send_chat(...args: any[]): unknown;
	send_chat_to(...args: any[]): unknown;
	send_rpc_error(...args: any[]): unknown;
	send_rpc_request(...args: any[]): unknown;
	send_rpc_result(...args: any[]): unknown;
	serverinfo_get(...args: any[]): unknown;
	serverinfo_request(...args: any[]): unknown;
	serverlist_get(...args: any[]): unknown;
	serverlist_reset(...args: any[]): unknown;
	serverlist_search(...args: any[]): unknown;
	set_coalition(...args: any[]): unknown;
	set_name(...args: any[]): unknown;
	set_slot(...args: any[]): unknown;
	spawn_player(...args: any[]): unknown;
	start_client(...args: any[]): unknown;
	start_server(...args: any[]): unknown;
	stop_game(...args: any[]): unknown;
	stop_network(...args: any[]): unknown;
	trace(...args: any[]): unknown;
}
