/**
 * @version 2.9.10.4160
 * @noSelf
 **/
export interface _env {
	warning(...args: any[]): unknown;
	setErrorMessageBoxEnabled(...args: any[]): unknown;
	showTraining(...args: any[]): unknown;
	info(...args: any[]): unknown;
	getValueDictByKey(...args: any[]): unknown;
	warehouses: {
		airports: {
			15: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			30: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			31: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			16: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			32: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			17: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			18: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			19: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			20: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			21: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			22: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			23: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			12: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			24: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			25: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			13: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			26: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			27: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			14: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			28: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
			29: {
				gasoline: { InitFuel: number };
				unlimitedMunitions: boolean;
				dynamicCargo: boolean;
				OperatingLevel_Air: number;
				diesel: { InitFuel: number };
				speed: number;
				dynamicSpawn: boolean;
				unlimitedAircrafts: boolean;
				unlimitedFuel: boolean;
				size: number;
				jet_fuel: { InitFuel: number };
				suppliers: {};
				coalition: string;
				methanol_mixture: { InitFuel: number };
				OperatingLevel_Eqp: number;
				allowHotStart: boolean;
				aircrafts: {};
				weapons: {};
				OperatingLevel_Fuel: number;
				periodicity: number;
			};
		};
		warehouses: {};
	};
	Mode: {
		USER: number;
		INIT: number;
		STOP: number;
		SIMULATION: number;
		START: number;
		FINISH: number;
	};
	error(...args: any[]): unknown;
	mission: {
		requiredModules: {};
		date: { Day: number; Year: number; Month: number };
		start_time: number;
		maxDictId: number;
		descriptionNeutralsTask: string;
		pictureFileNameN: {};
		failures: {};
		currentKey: number;
		pictureFileNameServer: {};
		weather: {
			atmosphere_type: number;
			wind: {
				at8000: { speed: number; dir: number };
				at2000: { speed: number; dir: number };
				atGround: { speed: number; dir: number };
			};
			enable_fog: boolean;
			visibility: { distance: number };
			halo: { preset: string };
			fog: { visibility: number; thickness: number };
			season: { temperature: number };
			type_weather: number;
			qnh: number;
			cyclones: {};
			name: string;
			dust_density: number;
			modifiedTime: boolean;
			groundTurbulence: number;
			enable_dust: boolean;
			clouds: {
				thickness: number;
				density: number;
				preset: string;
				base: number;
				iprecptns: number;
			};
		};
		result: {
			total: number;
			offline: { conditions: {}; actions: {}; func: {} };
			blue: { conditions: {}; actions: {}; func: {} };
			red: { conditions: {}; actions: {}; func: {} };
		};
		groundControl: {
			passwords: {
				artillery_commander: {};
				instructor: {};
				forward_observer: {};
				observer: {};
			};
			isPilotControlVehicles: boolean;
			roles: {
				artillery_commander: { blue: number; neutrals: number; red: number };
				instructor: { blue: number; neutrals: number; red: number };
				forward_observer: { blue: number; neutrals: number; red: number };
				observer: { blue: number; neutrals: number; red: number };
			};
		};
		map: { centerY: number; zoom: number; centerX: number };
		coalitions: {
			neutrals: {
				27: number;
				2: number;
				38: number;
				3: number;
				54: number;
				4: number;
				5: number;
				6: number;
				7: number;
				8: number;
				10: number;
				12: number;
				14: number;
				16: number;
				20: number;
				24: number;
				28: number;
				32: number;
				40: number;
				48: number;
				56: number;
				33: number;
				41: number;
				49: number;
				57: number;
				17: number;
				21: number;
				25: number;
				29: number;
				34: number;
				42: number;
				50: number;
				58: number;
				59: number;
				55: number;
				35: number;
				9: number;
				11: number;
				13: number;
				15: number;
				18: number;
				22: number;
				26: number;
				30: number;
				36: number;
				44: number;
				52: number;
				51: number;
				47: number;
				46: number;
				39: number;
				43: number;
				37: number;
				45: number;
				53: number;
				1: number;
				19: number;
				23: number;
				31: number;
			};
			blue: {
				1: number;
				2: number;
				4: number;
				8: number;
				16: number;
				17: number;
				9: number;
				18: number;
				5: number;
				10: number;
				20: number;
				21: number;
				11: number;
				22: number;
				3: number;
				6: number;
				12: number;
				13: number;
				7: number;
				14: number;
				19: number;
				15: number;
			};
			red: {
				7: number;
				1: number;
				2: number;
				4: number;
				8: number;
				9: number;
				5: number;
				10: number;
				3: number;
				6: number;
				11: number;
			};
		};
		descriptionText: string;
		pictureFileNameR: {};
		theatre: string;
		version: number;
		triggers: { zones: {} };
		coalition: {
			neutrals: {
				bullseye: { y: number; x: number };
				nav_points: {};
				name: string;
				country: {};
			};
			blue: {
				bullseye: { y: number; x: number };
				nav_points: {};
				name: string;
				country: {};
			};
			red: {
				bullseye: { y: number; x: number };
				nav_points: {};
				name: string;
				country: {};
			};
		};
		pictureFileNameB: {};
		sortie: string;
		descriptionBlueTask: string;
		goals: {};
		descriptionRedTask: string;
		trigrules: {};
		forcedOptions: {};
		trig: {
			custom: {};
			customStartup: {};
			events: {};
			func: {};
			flag: {};
			conditions: {};
			actions: {};
			funcStartup: {};
		};
	};
}
