export const config = {
	scripts: [
		{
			env: "mission" as const,
			luascript: "scripts/export.bridge.lua",
			outdir: "src/exports",
			namespaces: [
				"AI",
				"Airbase",
				"atmosphere",
				"coalition",
				"Controller",
				"coord",
				"env",
				"Group",
				"land",
				"missionCommands",
				"net",
				"Object",
				"radio",
				"StaticObject",
				"timer",
				"trigger",
				"Unit",
				"Warehouse",
				"Weapon",
				"world",
			],
		},
	],
};
