/**
 * Generates tests/corpus.ts: Base64 test vectors whose expected values come
 * from Node's Buffer, an implementation independent of the one under test.
 *
 * Deterministic (seeded PRNG), so regenerating yields an identical file:
 *   npm run generate:corpus --workspace=@flying-dice/tslua-base64
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "tests", "corpus.ts");

function mulberry32(seed) {
	return () => {
		seed = (seed + 0x6d2b79f5) | 0;
		let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}
const random = mulberry32(0x5eed);
const randomBytes = (length) => Buffer.from(Array.from({ length }, () => Math.floor(random() * 256)));

const inputs = [];
const add = (label, buffer) => inputs.push({ label, buffer });

add("empty", Buffer.alloc(0));
for (const text of ["f", "fo", "foo", "foob", "fooba", "foobar"]) add(`rfc4648 ${text}`, Buffer.from(text));
add("readme example", Buffer.from("return 1 + 1"));
add("utf-8 text", Buffer.from("héllo wörld ✈ DCS — Ж 日本 🚀"));
add("json text", Buffer.from('{"unit":"F-16C","alt":7620.5,"tags":["a","b"]}'));
for (let byte = 0; byte < 256; byte++) add(`byte ${byte}`, Buffer.from([byte]));
for (const pair of [[0, 0], [255, 255], [0, 255], [255, 0], [0xfb, 0xff], [0xff, 0xfe], [0x3e, 0x3f]]) {
	add(`pair ${pair.join(",")}`, Buffer.from(pair));
}
add("all bytes ascending", Buffer.from(Array.from({ length: 256 }, (_, i) => i)));
add("all bytes descending", Buffer.from(Array.from({ length: 256 }, (_, i) => 255 - i)));
add("zeros 57", Buffer.alloc(57));
add("0xff 58", Buffer.alloc(58, 0xff));
for (let i = 0; i < 160; i++) {
	const length = Math.floor(random() * 200);
	add(`random ${i} (${length} bytes)`, randomBytes(length));
}
// Straddle the implementation's 3072-byte read chunk and the 4096-byte decode chunk.
for (const length of [3071, 3072, 3073, 4095, 4096, 4097, 9217]) add(`random ${length} bytes`, randomBytes(length));

const rows = inputs.map(({ label, buffer }) => {
	const standard = buffer.toString("base64");
	const url = buffer.toString("base64url"); // Node omits padding for base64url
	return `\t[${JSON.stringify(label)}, "${buffer.toString("hex")}", "${standard}", "${url}"],`;
});

writeFileSync(
	out,
	`// Generated by scripts/generate-corpus.mjs from Node's Buffer. Do not edit by hand.
// [label, input bytes as hex, standard padded base64, url-safe unpadded base64]
export const CORPUS: [string, string, string, string][] = [
${rows.join("\n")}
];
`,
);
console.log(`Wrote ${inputs.length} vectors to ${out}`);
